package com.campuslab.user;

import org.junit.jupiter.api.Test;
import static org.assertj.core.api.Assertions.assertThat;

import java.time.Instant;
import java.util.UUID;

/**
 * Unit tests for the User entity.
 * Tests the basic functionality of the User class including constructors,
 * getters, setters, and enum values.
 * 
 * Requirements: 1.1, 1.4
 */
class UserTest {

    @Test
    void shouldCreateUserWithDefaultConstructor() {
        // Given & When
        User user = new User();
        
        // Then
        assertThat(user).isNotNull();
        assertThat(user.getId()).isNull(); // ID is generated by JPA
        assertThat(user.getName()).isNull();
        assertThat(user.getEmail()).isNull();
        assertThat(user.getPassword()).isNull();
        assertThat(user.getRole()).isNull();
        assertThat(user.getCreatedAt()).isNull(); // Timestamps managed by Hibernate
        assertThat(user.getUpdatedAt()).isNull();
    }

    @Test
    void shouldCreateUserWithParameterizedConstructor() {
        // Given
        String name = "João Silva";
        String email = "joao.silva@campus.edu";
        String password = "hashedPassword123";
        UserRole role = UserRole.ALUNO;
        
        // When
        User user = new User(name, email, password, role);
        
        // Then
        assertThat(user.getName()).isEqualTo(name);
        assertThat(user.getEmail()).isEqualTo(email);
        assertThat(user.getPassword()).isEqualTo(password);
        assertThat(user.getRole()).isEqualTo(role);
    }

    @Test
    void shouldSetAndGetAllProperties() {
        // Given
        User user = new User();
        String name = "Maria Santos";
        String email = "maria.santos@campus.edu";
        String password = "newHashedPassword456";
        UserRole role = UserRole.PROFESSOR;
        
        // When
        user.setName(name);
        user.setEmail(email);
        user.setPassword(password);
        user.setRole(role);
        
        // Then
        assertThat(user.getName()).isEqualTo(name);
        assertThat(user.getEmail()).isEqualTo(email);
        assertThat(user.getPassword()).isEqualTo(password);
        assertThat(user.getRole()).isEqualTo(role);
    }

    @Test
    void shouldSupportAlunoRole() {
        // Given
        User user = new User();
        
        // When
        user.setRole(UserRole.ALUNO);
        
        // Then
        assertThat(user.getRole()).isEqualTo(UserRole.ALUNO);
        assertThat(user.getRole().name()).isEqualTo("ALUNO");
    }

    @Test
    void shouldSupportProfessorRole() {
        // Given
        User user = new User();
        
        // When
        user.setRole(UserRole.PROFESSOR);
        
        // Then
        assertThat(user.getRole()).isEqualTo(UserRole.PROFESSOR);
        assertThat(user.getRole().name()).isEqualTo("PROFESSOR");
    }

    @Test
    void userRoleEnumShouldHaveExactlyTwoValues() {
        // Given & When
        UserRole[] roles = UserRole.values();
        
        // Then
        assertThat(roles).hasSize(2);
        assertThat(roles).containsExactlyInAnyOrder(UserRole.ALUNO, UserRole.PROFESSOR);
    }

    @Test
    void userRoleEnumShouldBeCreatedFromString() {
        // Given & When & Then
        assertThat(UserRole.valueOf("ALUNO")).isEqualTo(UserRole.ALUNO);
        assertThat(UserRole.valueOf("PROFESSOR")).isEqualTo(UserRole.PROFESSOR);
    }
}